/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagementsystem;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;

/**
 *
 * @author Sultan
 */
public class CreateCompanyForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateCompanyForm
     */
    Connection c = null;
    Statement s = null;
    ResultSet rs = null;
    String a = "";

    public CreateCompanyForm() {
        initComponents();
        c = DB.java_db();
        
        //Full screen
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        //Setting validation error messages to null when this form is opened
        error1.setText("");
        error2.setText("");
        error3.setText("");
        error4.setText("");
        error5.setText("");
        error6.setText("");
        error7.setText("");
        error8.setText("");
        error9.setText("");
        error10.setText("");
        error11.setText("");
        error12.setText("");
        error13.setText("");
        error14.setText("");
        error15.setText("");
        error16.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        error1 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        middleName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        error4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        error5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        show = new javax.swing.JButton();
        error6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        error7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        state = new javax.swing.JComboBox<>();
        error8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        error9 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        error10 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        error11 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gstin = new javax.swing.JTextField();
        error12 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bankName = new javax.swing.JComboBox<>();
        error13 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bankBranch = new javax.swing.JComboBox<>();
        error14 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bankAcNumber = new javax.swing.JTextField();
        error15 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bankIFSC = new javax.swing.JTextField();
        error16 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Create Company");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        error1.setForeground(new java.awt.Color(255, 0, 0));
        error1.setText("error1");

        firstName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                firstNameCaretUpdate(evt);
            }
        });
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });

        jLabel1.setText("First Name :");

        error2.setForeground(new java.awt.Color(255, 0, 0));
        error2.setText("error2");

        middleName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                middleNameCaretUpdate(evt);
            }
        });
        middleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                middleNameFocusLost(evt);
            }
        });

        jLabel2.setText("Middle Name :");

        error3.setForeground(new java.awt.Color(255, 0, 0));
        error3.setText("error3");

        lastName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                lastNameCaretUpdate(evt);
            }
        });
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });

        jLabel3.setText("Last Name :");

        jLabel4.setText("Company Name :");

        companyName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                companyNameCaretUpdate(evt);
            }
        });

        error4.setForeground(new java.awt.Color(255, 0, 0));
        error4.setText("error4");

        jLabel5.setText("Username :");

        username.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                usernameCaretUpdate(evt);
            }
        });

        error5.setForeground(new java.awt.Color(255, 0, 0));
        error5.setText("error5");

        jLabel6.setText("Password :");

        password.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passwordCaretUpdate(evt);
            }
        });

        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        error6.setForeground(new java.awt.Color(255, 0, 0));
        error6.setText("error6");

        jLabel7.setText("Address :");

        address.setColumns(20);
        address.setRows(5);
        address.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                addressCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(address);

        error7.setForeground(new java.awt.Color(255, 0, 0));
        error7.setText("error7");

        jLabel16.setText("State :");

        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Goa", "Maharashtra" }));
        state.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stateItemStateChanged(evt);
            }
        });

        error8.setForeground(new java.awt.Color(255, 0, 0));
        error8.setText("error8");

        jLabel8.setText("E-Mail :");

        email.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                emailCaretUpdate(evt);
            }
        });
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        error9.setForeground(new java.awt.Color(255, 0, 0));
        error9.setText("error9");

        jLabel9.setText("Phone Number :");

        phone.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                phoneCaretUpdate(evt);
            }
        });
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });

        error10.setForeground(new java.awt.Color(255, 0, 0));
        error10.setText("error10");

        jLabel10.setText("Mobile Number :");

        mobile.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                mobileCaretUpdate(evt);
            }
        });
        mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileFocusLost(evt);
            }
        });

        error11.setForeground(new java.awt.Color(255, 0, 0));
        error11.setText("error11");

        jLabel11.setText("GSTIN :");

        gstin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                gstinCaretUpdate(evt);
            }
        });
        gstin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gstinFocusLost(evt);
            }
        });

        error12.setForeground(new java.awt.Color(255, 0, 0));
        error12.setText("error12");

        jLabel12.setText("Bank Name :");

        bankName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "IDBI Bank", "Urban Bank", "ICICI Bank" }));
        bankName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bankNameItemStateChanged(evt);
            }
        });

        error13.setForeground(new java.awt.Color(255, 0, 0));
        error13.setText("error13");

        jLabel13.setText("Bank Branch :");

        bankBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Dapoli", "Khed", "Chiplun" }));
        bankBranch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bankBranchItemStateChanged(evt);
            }
        });

        error14.setForeground(new java.awt.Color(255, 0, 0));
        error14.setText("error14");

        jLabel14.setText("Bank A/c Number :");

        bankAcNumber.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                bankAcNumberCaretUpdate(evt);
            }
        });
        bankAcNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankAcNumberFocusLost(evt);
            }
        });

        error15.setForeground(new java.awt.Color(255, 0, 0));
        error15.setText("error15");

        jLabel15.setText("Bank IFSC :");

        bankIFSC.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                bankIFSCCaretUpdate(evt);
            }
        });
        bankIFSC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankIFSCFocusLost(evt);
            }
        });

        error16.setForeground(new java.awt.Color(255, 0, 0));
        error16.setText("error16");

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bankIFSC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(error16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bankAcNumber))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bankBranch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error13)
                            .addComponent(error14)
                            .addComponent(error15)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(middleName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(error2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(error1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(error3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(companyName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(error4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(show))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error5)
                            .addComponent(error6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(state, 0, 220, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(error8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gstin))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mobile))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error9)
                            .addComponent(error10)
                            .addComponent(error11)
                            .addComponent(error12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {companyName, lastName, middleName, state, username});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstName)
                    .addComponent(error1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(middleName)
                    .addComponent(error2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(error3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(companyName)
                    .addComponent(error4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(username)
                    .addComponent(error5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show)
                    .addComponent(error6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(error8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(gstin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bankName)
                    .addComponent(error13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(bankBranch)
                    .addComponent(error14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bankAcNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(bankIFSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error16))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void middleNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_middleNameCaretUpdate
        //Will display error msg if number added in name
        error2.setText("");
        String middleName1 = this.middleName.getText();
        Pattern p = Pattern.compile("^[a-zA-Z\\s]*$");
        Matcher m = p.matcher(middleName1);
        if (!m.matches()) {
            error2.setText("Invalid Middle Name!");
        }
    }//GEN-LAST:event_middleNameCaretUpdate

    private void lastNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_lastNameCaretUpdate
        //Will display error msg if number added in name
        error3.setText("");
        String lastName1 = this.lastName.getText();
        Pattern p = Pattern.compile("^[a-zA-Z\\s]*$");
        Matcher m = p.matcher(lastName1);
        if (!m.matches()) {
            error3.setText("Invalid Last Name!");
        }
    }//GEN-LAST:event_lastNameCaretUpdate

    private void companyNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_companyNameCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error4.setText("");
    }//GEN-LAST:event_companyNameCaretUpdate

    private void usernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_usernameCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error5.setText("");
    }//GEN-LAST:event_usernameCaretUpdate

    private void passwordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passwordCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error6.setText("");
    }//GEN-LAST:event_passwordCaretUpdate

    private void addressCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_addressCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error7.setText("");
    }//GEN-LAST:event_addressCaretUpdate

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        //Will display error msg after focus has been lost if wrong email address is entered
        error9.setText("");
        String email1 = this.email.getText();
        Pattern p = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$|^$", Pattern.CASE_INSENSITIVE);
        Matcher m = p.matcher(email1);
        if (!m.matches()) {
            error9.setText("Invalid E-Mail Address!");
        }
    }//GEN-LAST:event_emailFocusLost

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        //Will display error msg after focus has been lost if wrong phone number is entered
        error10.setText("");
        String phone1 = this.phone.getText();
        Pattern p = Pattern.compile("\\d{11}|\\(\\d{5}\\)\\d{6}|(?:\\d{5}-)\\d{6}|^$");
        Matcher m = p.matcher(phone1);
        if (!m.matches()) {
            error10.setText("Invalid Phone Number!");
        }
    }//GEN-LAST:event_phoneFocusLost

    private void mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusLost
        //Will display error msg after focus has been lost if wrong mobile number is entered
        error11.setText("");
        String mobile1 = this.mobile.getText();
        Pattern p = Pattern.compile("^[6-9]\\d{9}$|^$");
        Matcher m = p.matcher(mobile1);
        if (!m.matches()) {
            error11.setText("Invalid Mobile Number!");
        }
    }//GEN-LAST:event_mobileFocusLost

    private void gstinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gstinFocusLost
        //Will display error msg after focus has been lost if wrong gstin is entered
        error12.setText("");
        String gstin1 = this.gstin.getText();
        Pattern p = Pattern.compile("^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{3}$|^$");
        Matcher m = p.matcher(gstin1);
        if (!m.matches()) {
            error12.setText("Invalid GSTIN!");
        }
    }//GEN-LAST:event_gstinFocusLost

    private void bankAcNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankAcNumberFocusLost
        //Will display error msg after focus has been lost if wrong bank a/c number is entered
        error15.setText("");
        String bankAcNumber1 = this.bankAcNumber.getText();
        Pattern p = Pattern.compile("^\\d{9,18}$|^$");
        Matcher m = p.matcher(bankAcNumber1);
        if (!m.matches()) {
            error15.setText("Invalid Bank Account Number!");
        }
    }//GEN-LAST:event_bankAcNumberFocusLost

    private void bankIFSCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankIFSCFocusLost
        //Will display error msg after focus has been lost if wrong bank ifsc is entered
        error16.setText("");
        String bankIFSC1 = this.bankIFSC.getText();
        Pattern p = Pattern.compile("^[A-Za-z]{4}[a-zA-Z0-9]{7}$|^$");
        Matcher m = p.matcher(bankIFSC1);
        if (!m.matches()) {
            error16.setText("Invalid Bank IFSC!");
        }
    }//GEN-LAST:event_bankIFSCFocusLost

    private void emailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_emailCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error9.setText("");
    }//GEN-LAST:event_emailCaretUpdate

    private void phoneCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_phoneCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error10.setText("");
    }//GEN-LAST:event_phoneCaretUpdate

    private void mobileCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_mobileCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error11.setText("");
    }//GEN-LAST:event_mobileCaretUpdate

    private void gstinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_gstinCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error12.setText("");
    }//GEN-LAST:event_gstinCaretUpdate

    private void bankAcNumberCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_bankAcNumberCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error15.setText("");
    }//GEN-LAST:event_bankAcNumberCaretUpdate

    private void bankIFSCCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_bankIFSCCaretUpdate
        //Will remove error msg on clicking this field if error already exists
        error16.setText("");
    }//GEN-LAST:event_bankIFSCCaretUpdate

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        //Will create a company and add all the info in database

        //Taking all the entered values in their respective strings
        String firstName1 = this.firstName.getText();
        String middleName1 = this.middleName.getText();
        String lastName1 = this.lastName.getText();
        String companyName1 = this.companyName.getText();
        String username1 = this.username.getText();
        String password1 = this.password.getText();
        String address1 = this.address.getText();
        String state1 = this.state.getSelectedItem().toString();
        String email1 = this.email.getText();
        String phone1 = this.phone.getText();
        String mobile1 = this.mobile.getText();
        String gstin1 = this.gstin.getText();
        String bankName1 = this.bankName.getSelectedItem().toString();
        String bankBranch1 = this.bankBranch.getSelectedItem().toString();
        String bankAcNumber1 = this.bankAcNumber.getText();
        String bankIFSC1 = this.bankIFSC.getText();

        //Setting all error msg to null
        error1.setText("");
        error2.setText("");
        error3.setText("");
        error4.setText("");
        error5.setText("");
        error6.setText("");
        error7.setText("");
        error8.setText("");
        error9.setText("");
        error10.setText("");
        error11.setText("");
        error12.setText("");
        error13.setText("");
        error14.setText("");
        error15.setText("");
        error16.setText("");

        //Required field validations
        int reqFlag = 0;
        int reqFlag1, reqFlag2, reqFlag3, reqFlag4, reqFlag5, reqFlag6, reqFlag7, reqFlag8,
                reqFlag9, reqFlag10, reqFlag11, reqFlag12, reqFlag13, reqFlag14, reqFlag15, reqFlag16;
        reqFlag1 = reqFlag2 = reqFlag3 = reqFlag4 = reqFlag5 = reqFlag6 = reqFlag7 = reqFlag8
                = reqFlag9 = reqFlag10 = reqFlag11 = reqFlag12 = reqFlag13 = reqFlag14 = reqFlag15 = reqFlag16 = 0;
        if (firstName1.equals("")) {
            error1.setText("First Name Required!");
            reqFlag1 = 1;
        } else {
            reqFlag1 = 0;
        }
        if (middleName1.equals("")) {
            error2.setText("Middle Name Required!");
            reqFlag2 = 1;
        } else {
            reqFlag2 = 0;
        }
        if (lastName1.equals("")) {
            error3.setText("Last Name Required!");
            reqFlag3 = 1;
        } else {
            reqFlag3 = 0;
        }
        if (companyName1.equals("")) {
            error4.setText("Company Name Required!");
            reqFlag4 = 1;
        } else {
            reqFlag4 = 0;
        }
        if (username1.equals("")) {
            error5.setText("Username Required!");
            reqFlag5 = 1;
        } else {
            reqFlag5 = 0;
        }
        if (password1.equals("")) {
            error6.setText("Password Required!");
            reqFlag6 = 1;
        } else {
            reqFlag6 = 0;
        }
        if (address1.equals("")) {
            error7.setText("Address Required!");
            reqFlag7 = 1;
        } else {
            reqFlag7 = 0;
        }
        if (state1.equals(" ")) {
            error8.setText("State Required!");
            reqFlag8 = 1;
        } else {
            reqFlag8 = 0;
        }
        if (email1.equals("")) {
            error9.setText("E-Mail Address Required!");
            reqFlag9 = 1;
        } else {
            reqFlag9 = 0;
        }
        if (phone1.equals("")) {
            if (mobile.equals("")) {
                error10.setText("Phone Number Required!");
                reqFlag10 = 1;
            } else {
                reqFlag10 = 0;
            }
        }
        if (mobile1.equals("")) {
            error11.setText("Mobile Number Required!");
            reqFlag11 = 1;
        } else {
            reqFlag11 = 0;
        }
        if (gstin1.equals("")) {
            error12.setText("GSTIN Required!");
            reqFlag12 = 1;
        } else {
            reqFlag12 = 0;
        }
        if (bankName1.equals(" ")) {
            error13.setText("Bank Name Required!");
            reqFlag13 = 1;
        } else {
            reqFlag13 = 0;
        }
        if (bankBranch1.equals(" ")) {
            error14.setText("Bank Branch Required!");
            reqFlag14 = 1;
        } else {
            reqFlag14 = 0;
        }
        if (bankAcNumber1.equals("")) {
            error15.setText("Bank Account Number Required!");
            reqFlag15 = 1;
        } else {
            reqFlag15 = 0;
        }
        if (bankIFSC1.equals("")) {
            error16.setText("Bank IFSC Required!");
            reqFlag16 = 1;
        } else {
            reqFlag16 = 0;
        }
        if (reqFlag1 == 1 || reqFlag2 == 1 || reqFlag3 == 1 || reqFlag4 == 1
                || reqFlag5 == 1 || reqFlag6 == 1 || reqFlag7 == 1 || reqFlag8 == 1
                || reqFlag9 == 1 || (reqFlag10 == 1 && reqFlag11 == 1) || reqFlag11 == 1
                || reqFlag12 == 1 || reqFlag13 == 1 || reqFlag14 == 1 || reqFlag15 == 1 || reqFlag16 == 1) {
            reqFlag = 1;
        } else {
            reqFlag = 0;
        }

        //Regular expression validations
        int regFlag = 0;
        int regFlag1, regFlag2, regFlag3, regFlag4, regFlag5, regFlag6, regFlag7, regFlag8, regFlag9;
        regFlag1 = regFlag2 = regFlag3 = regFlag4 = regFlag5 = regFlag6 = regFlag7 = regFlag8 = regFlag9 = 0;
        Pattern namePattern = Pattern.compile("^[a-zA-Z\\s]*$");
        Pattern emailPattern = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$|^$", Pattern.CASE_INSENSITIVE);
        Pattern phonePattern = Pattern.compile("\\d{11}|\\(\\d{5}\\)\\d{6}|(?:\\d{5}-)\\d{6}|^$");
        Pattern mobilePattern = Pattern.compile("^[6-9]\\d{9}$|^$");
        Pattern gstinPattern = Pattern.compile("^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$|^$");
        Pattern bankAcNumberPattern = Pattern.compile("^\\d{9,18}$|^$");
        Pattern bankIFSCPattern = Pattern.compile("^[A-Za-z]{4}[a-zA-Z0-9]{7}$|^$");
        Matcher firstNameMatcher = namePattern.matcher(firstName1);
        if (!firstNameMatcher.matches()) {
            error1.setText("Invalid First Name!");
            regFlag1 = 1;
        } else {
            regFlag1 = 0;
        }
        Matcher middleNameMatcher = namePattern.matcher(middleName1);
        if (!middleNameMatcher.matches()) {
            error2.setText("Invalid Middle Name!");
            regFlag2 = 1;
        } else {
            regFlag2 = 0;
        }
        Matcher lastNameMatcher = namePattern.matcher(lastName1);
        if (!lastNameMatcher.matches()) {
            error3.setText("Invalid Last Name!");
            regFlag3 = 1;
        } else {
            regFlag3 = 0;
        }
        Matcher emailMatcher = emailPattern.matcher(email1);
        if (!emailMatcher.matches()) {
            error9.setText("Invalid E-Mail Address!");
            regFlag4 = 1;
        } else {
            regFlag4 = 0;
        }
        Matcher phoneNumberMatcher = phonePattern.matcher(phone1);
        if (!phoneNumberMatcher.matches()) {
            error10.setText("Invalid Phone Number!");
            regFlag5 = 1;
        } else {
            regFlag5 = 0;
        }
        Matcher mobileNumberMatcher = mobilePattern.matcher(mobile1);
        if (!mobileNumberMatcher.matches()) {
            error11.setText("Invalid Mobile Number!");
            regFlag6 = 1;
        } else {
            regFlag6 = 0;
        }
        Matcher gstinMatcher = gstinPattern.matcher(gstin1);
        if (!gstinMatcher.matches()) {
            error12.setText("Invalid GSTIN!");
            regFlag7 = 1;
        } else {
            regFlag7 = 0;
        }
        Matcher bankAcNumberMatcher = bankAcNumberPattern.matcher(bankAcNumber1);
        if (!bankAcNumberMatcher.matches()) {
            error15.setText("Invalid Bank Account Number!");
            regFlag8 = 1;
        } else {
            regFlag8 = 0;
        }
        Matcher bankIFSCMatcher = bankIFSCPattern.matcher(bankIFSC1);
        if (!bankIFSCMatcher.matches()) {
            error16.setText("Invalid Bank IFSC!");
            regFlag9 = 1;
        } else {
            regFlag9 = 0;
        }
        if (regFlag1 == 1 || regFlag2 == 1 || regFlag3 == 1 || regFlag4 == 1
                || regFlag5 == 1 || regFlag6 == 1 || regFlag7 == 1 || regFlag8 == 1 || regFlag9 == 1) {
            regFlag = 1;
        } else {
            regFlag = 0;
        }

        //Duplicate entries validations
        int dupFlag = 0;
        int dupFlag1, dupFlag2, dupFlag3, dupFlag4, dupFlag5, dupFlag6, dupFlag7, dupFlag8;
        dupFlag1 = dupFlag2 = dupFlag3 = dupFlag4 = dupFlag5 = dupFlag6 = dupFlag7 = dupFlag8 = 0;
        try {
            //Connection c = DriverManager.getConnection("jdbc:derby://localhost:1527/SMSDB", "sultan", "sultan");
            s = c.createStatement();
            String sql = "SELECT * FROM company";
            rs = s.executeQuery(sql);
            while (rs.next()) {
                String companyName = rs.getString("companyName");
                String username = rs.getString("username");
                String email = rs.getString("email");
                String phone = rs.getString("phone");
                String mobile = rs.getString("mobile");
                String gstin = rs.getString("gstin");
                String bankAcNumber = rs.getString("bankAcNumber");
                String bankIFSC = rs.getString("bankIFSC");
                if (companyName1.equalsIgnoreCase(companyName)) {
                    error4.setText("Company Name Already Exists!");
                    dupFlag1 = 1;
                } else {
                    dupFlag1 = 0;
                }
                if (username1.equals(username)) {
                    error5.setText("Username Already Exists!");
                    dupFlag2 = 1;
                } else {
                    dupFlag2 = 0;
                }
                if (email1.equalsIgnoreCase(email)) {
                    error9.setText("E-Mail Already Exists!");
                    dupFlag3 = 1;
                } else {
                    dupFlag3 = 0;
                }
                if (!phone1.equals("")) {
                    if (phone1.equals(phone)) {
                        error10.setText("Phone Number Already Exists!");
                        dupFlag4 = 1;
                    } else {
                        dupFlag4 = 0;
                    }
                }
                if (mobile1.equals(mobile)) {
                    error11.setText("Mobile Number Already Exists!");
                    dupFlag5 = 1;
                } else {
                    dupFlag5 = 0;
                }
                if (gstin1.equals(gstin)) {
                    error12.setText("GSTIN Already Exists!");
                    dupFlag6 = 1;
                } else {
                    dupFlag6 = 0;
                }
                if (bankAcNumber1.equals(bankAcNumber)) {
                    error15.setText("Bank Account Number Already Exists!");
                    dupFlag7 = 1;
                } else {
                    dupFlag7 = 0;
                }
                if (bankIFSC1.equals(bankIFSC)) {
                    error16.setText("Bank IFSC Already Exists!");
                    dupFlag8 = 1;
                } else {
                    dupFlag8 = 0;
                }
                if (dupFlag1 == 1 || dupFlag2 == 1 || dupFlag3 == 1 || dupFlag4 == 1
                        || dupFlag5 == 1 || dupFlag6 == 1 || dupFlag7 == 1 || dupFlag8 == 1) {
                    dupFlag = 1;
                    break;
                } else {
                    dupFlag = 0;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }finally {
            try {
                s.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }

        //Adding data to database only if all the flags are 0
        if (reqFlag == 0 && regFlag == 0 && dupFlag == 0) {
            int ans = JOptionPane.showConfirmDialog(this, "Create company?", "Company creation", JOptionPane.YES_NO_OPTION);
            if (ans == 0) {
                try {
//                    Connection c = DriverManager.getConnection("jdbc:derby://localhost:1527/SMSDB", "sultan", "sultan");
                    s = c.createStatement();
                    String sql3 = "INSERT INTO company(firstName,middleName,lastName,companyName,username,"
                            + "password,address,state,email,phone,mobile,gstin,bankName,bankBranch,"
                            + "bankAcNumber,bankIFSC) VALUES('" + firstName1 + "','" + middleName1 + "'"
                            + ",'" + lastName1 + "','" + companyName1 + "','" + username1 + "','" + password1 + "','" + address1 + "'"
                            + ",'" + state1 + "','" + email1 + "','" + phone1 + "','" + mobile1 + "','" + gstin1 + "','" + bankName1 + "',"
                            + "'" + bankBranch1 + "','" + bankAcNumber1 + "','" + bankIFSC1 + "')";
                    s.executeUpdate(sql3);
                    JOptionPane.showMessageDialog(this, "Company created successfully!");
                    //Closing this form and opening LoginForm again
                    this.dispose();
                    new LoginForm().setVisible(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }finally {
            try {
                s.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
            }
        }
    }//GEN-LAST:event_createActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        //Will clear all textboxes, comboboxes and validation error msgs to null 
        firstName.setText("");
        middleName.setText("");
        lastName.setText("");
        companyName.setText("");
        username.setText("");
        password.setText("");
        address.setText("");
        state.setSelectedItem(" ");
        email.setText("");
        phone.setText("");
        mobile.setText("");
        gstin.setText("");
        bankName.setSelectedItem(" ");
        bankBranch.setSelectedItem(" ");
        bankAcNumber.setText("");
        bankIFSC.setText("");
        error1.setText("");
        error2.setText("");
        error3.setText("");
        error4.setText("");
        error5.setText("");
        error6.setText("");
        error7.setText("");
        error8.setText("");
        error9.setText("");
        error10.setText("");
        error11.setText("");
        error12.setText("");
        error13.setText("");
        error14.setText("");
        error15.setText("");
        error16.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        //Will show & hide the password when button is clicked
        if (a.equals("")) {
            password.setEchoChar((char) 0);
            a = "Set";
            show.setText("Hide");
        } else {
            password.setEchoChar('*');
            a = "";
            show.setText("Show");
        }
    }//GEN-LAST:event_showActionPerformed

    private void firstNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_firstNameCaretUpdate
        //Will display error msg if number added in name
        error1.setText("");
        String firstName1 = this.firstName.getText();
        Pattern p = Pattern.compile("^[a-zA-Z\\s]*$");
        Matcher m = p.matcher(firstName1);
        if (!m.matches()) {
            error1.setText("Invalid First Name!");
        }
    }//GEN-LAST:event_firstNameCaretUpdate

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        //Will go back to LoginForm.java
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void stateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stateItemStateChanged
        //Will remove error msg after selecting an item if it already exists
        String item = this.state.getSelectedItem().toString();
        if (!item.equals(" ")) {
            error8.setText("");
        }
    }//GEN-LAST:event_stateItemStateChanged

    private void bankNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bankNameItemStateChanged
        //Will remove error msg after selectin an item if it already exists
        String item = this.bankName.getSelectedItem().toString();
        if (!item.equals(" ")) {
            error13.setText("");
        }
    }//GEN-LAST:event_bankNameItemStateChanged

    private void bankBranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bankBranchItemStateChanged
        //Will remove error msg after selectin an item if it already exists
        String item = this.bankBranch.getSelectedItem().toString();
        if (!item.equals(" ")) {
            error14.setText("");
        }
    }//GEN-LAST:event_bankBranchItemStateChanged

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusLost
        // TODO add your handling code here:
        String firstName1 = this.firstName.getText();
        error1.setText("");
        if(firstName1.equals("")){
            error1.setText("First Name Required!");
        }
    }//GEN-LAST:event_firstNameFocusLost

    private void middleNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameFocusLost
        // TODO add your handling code here:
        String middleName1 = this.middleName.getText();
        error2.setText("");
        if(middleName1.equals("")){
            error2.setText("Middle Name Required!");
        }
    }//GEN-LAST:event_middleNameFocusLost

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        // TODO add your handling code here:
        String lastName1 = this.lastName.getText();
        error3.setText("");
        if(lastName1.equals("")){
            error3.setText("Last Name Required!");
        }
    }//GEN-LAST:event_lastNameFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCompanyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JButton back;
    private javax.swing.JTextField bankAcNumber;
    private javax.swing.JComboBox<String> bankBranch;
    private javax.swing.JTextField bankIFSC;
    private javax.swing.JComboBox<String> bankName;
    private javax.swing.JButton clear;
    private javax.swing.JTextField companyName;
    private javax.swing.JButton create;
    private javax.swing.JTextField email;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error10;
    private javax.swing.JLabel error11;
    private javax.swing.JLabel error12;
    private javax.swing.JLabel error13;
    private javax.swing.JLabel error14;
    private javax.swing.JLabel error15;
    private javax.swing.JLabel error16;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel error5;
    private javax.swing.JLabel error6;
    private javax.swing.JLabel error7;
    private javax.swing.JLabel error8;
    private javax.swing.JLabel error9;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField gstin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField middleName;
    private javax.swing.JTextField mobile;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton show;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
