/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagementsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sultan
 */
public class ProductListForm extends javax.swing.JFrame {

    /**
     * Creates new form ProductListForm
     */
    Connection c = null;
    Statement s = null;
    ResultSet rs = null;
    DefaultTableModel model;

    public ProductListForm() {
        initComponents();
        c = DB.java_db();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        productTable.getColumn("ID").setCellRenderer(centerRenderer);
        productTable.getColumn("Purchase Rate/Unit (Rs.)").setCellRenderer(centerRenderer);
        productTable.getColumn("Sale Rate/Unit (Rs.)").setCellRenderer(centerRenderer);
        productTable.getColumn("Quantity").setCellRenderer(centerRenderer);

        productTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        model = (DefaultTableModel) productTable.getModel();
        try {
            s = c.createStatement();
            rs = s.executeQuery("SELECT * FROM product");
            double totalStockAmount = 0.0;
            while (rs.next()) {
                String productID1 = rs.getString("productID");
                String productName1 = rs.getString("productName");
                String purchaseRate1 = rs.getString("purchaseRate");
                String saleRate1 = rs.getString("saleRate");
                totalStockAmount += Double.parseDouble(saleRate1);
                int quanity1 = rs.getInt("quantity");
                Object[] row = {productID1, productName1, purchaseRate1, saleRate1, quanity1};
                model.addRow(row);
            }
            this.totalAmt.setText("Total Stock Amount : "+totalStockAmount+" Rs.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(ProductListForm.this, e);
        } finally {
            try {
                rs.close();
                s.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(ProductListForm.this, e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalAmount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        detailsButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        productSelector = new javax.swing.JTextField();
        totalAmt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PRODUCT LIST");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("SEARCH CRITERIA :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 43, 226));
        jLabel2.setText("Product Name :");

        detailsButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        detailsButton.setForeground(new java.awt.Color(219, 112, 147));
        detailsButton.setText("Full Details");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Purchase Rate/Unit (Rs.)", "Sale Rate/Unit (Rs.)", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(productTable);

        productSelector.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                productSelectorCaretUpdate(evt);
            }
        });

        totalAmt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalAmt.setForeground(new java.awt.Color(138, 43, 226));
        totalAmt.setText("jLabel3");

        javax.swing.GroupLayout totalAmountLayout = new javax.swing.GroupLayout(totalAmount);
        totalAmount.setLayout(totalAmountLayout);
        totalAmountLayout.setHorizontalGroup(
            totalAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalAmountLayout.createSequentialGroup()
                .addGroup(totalAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, totalAmountLayout.createSequentialGroup()
                        .addGroup(totalAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(totalAmountLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1))
                            .addGroup(totalAmountLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(productSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(detailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 398, Short.MAX_VALUE))
                    .addGroup(totalAmountLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1)))
                .addGap(35, 35, 35))
            .addGroup(totalAmountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalAmountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalAmt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalAmountLayout.setVerticalGroup(
            totalAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalAmountLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(totalAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(productSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalAmt)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = this.productTable.getSelectedRow();
            String productSelector1 = (String) this.productTable.getValueAt(selectedRow, 1);
            if (productSelector1.equals("")) {
                JOptionPane.showMessageDialog(this, "No Product Selected!");
            } else {
                ProductSearchForm psf = new ProductSearchForm();
                psf.setVisible(true);
                psf.productName.setSelectedItem(productSelector1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No Product Selected!");
        }

    }//GEN-LAST:event_detailsButtonActionPerformed

    private void productSelectorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_productSelectorCaretUpdate
        // TODO add your handling code here:
        String productSelector1 = this.productSelector.getText();
        model.setRowCount(0);
        if (!productSelector1.equals("")) {
            try {
                s = c.createStatement();
                rs = s.executeQuery("SELECT * FROM product WHERE productName LIKE '" + productSelector1 + "%'");
                while (rs.next()) {
                    String productID1 = rs.getString("productID");
                    String productName1 = rs.getString("productName");
                    String purchaseRate1 = rs.getString("purchaseRate");
                    String saleRate1 = rs.getString("saleRate");
                    int quanity1 = rs.getInt("quantity");
                    Object[] row = {productID1, productName1, purchaseRate1, saleRate1, quanity1};
                    model.addRow(row);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            } finally {
                try {
                    rs.close();
                    s.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        } else {
            try {
                s = c.createStatement();
                rs = s.executeQuery("SELECT * FROM product");
                while (rs.next()) {
                    String productID1 = rs.getString("productID");
                    String productName1 = rs.getString("productName");
                    String purchaseRate1 = rs.getString("purchaseRate");
                    String saleRate1 = rs.getString("saleRate");
                    int quanity1 = rs.getInt("quantity");
                    Object[] row = {productID1, productName1, purchaseRate1, saleRate1, quanity1};
                    model.addRow(row);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            } finally {
                try {
                    rs.close();
                    s.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        }
    }//GEN-LAST:event_productSelectorCaretUpdate

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            c.close();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField productSelector;
    private javax.swing.JTable productTable;
    private javax.swing.JPanel totalAmount;
    private javax.swing.JLabel totalAmt;
    // End of variables declaration//GEN-END:variables
}
