/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagementsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Desktop
 */
public class ShopCreationForm3 extends javax.swing.JFrame {

    /**
     * Creates new form ShopCreationForm3
     */
    Connection c = null;
    Statement s = null;
    ResultSet rs = null;
    String a = "";
    String bankName2, bankBranch2, bankAcNumber2, bankIFSC2, shopName2, gstin2, username2, password2;
    String firstName3, middleName3, lastName3, streetAddress3, city3, state3, email3, phone3, mobile3;

    private void clearError() {
        this.error1.setText("");
        this.error2.setText("");
        this.error3.setText("");
        this.error4.setText("");
        this.error5.setText("");
        this.error6.setText("");
        this.error7.setText("");
        this.error8.setText("");
    }

    public ShopCreationForm3() {
        initComponents();

        c = DB.java_db();

        clearError();

        firstName3 = ShopCreationForm2.firstName2;
        middleName3 = ShopCreationForm2.middleName2;
        lastName3 = ShopCreationForm2.lastName2;
        streetAddress3 = ShopCreationForm2.streetAddress2;
        city3 = ShopCreationForm2.city2;
        state3 = ShopCreationForm2.state2;
        email3 = ShopCreationForm2.email2;
        phone3 = ShopCreationForm2.phone2;
        mobile3 = ShopCreationForm2.mobile2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bankName = new javax.swing.JComboBox<>();
        bankBranch = new javax.swing.JComboBox<>();
        bankAcNumber = new javax.swing.JTextField();
        bankIFSC = new javax.swing.JTextField();
        shopName = new javax.swing.JTextField();
        gstin = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();
        error5 = new javax.swing.JLabel();
        error6 = new javax.swing.JLabel();
        error7 = new javax.swing.JLabel();
        error8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        addButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        resetButton = new javax.swing.JButton();
        show = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD SHOP");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("BANK RELATED INFORMATION :");

        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Bank Name* :");

        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Branch* :");

        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Account Number* :");

        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("IFSC* :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("SHOP RELATED INFORMATION :");

        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Shop Name* :");

        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("GSTIN* :");

        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Username* :");

        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Password* :");

        bankName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "IDBI Bank", "Urban Bank", "ICICI Bank" }));
        bankName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bankNameItemStateChanged(evt);
            }
        });
        bankName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankNameFocusLost(evt);
            }
        });

        bankBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Dapoli", "Khed", "Chiplun" }));
        bankBranch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bankBranchItemStateChanged(evt);
            }
        });
        bankBranch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankBranchFocusLost(evt);
            }
        });

        bankAcNumber.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                bankAcNumberCaretUpdate(evt);
            }
        });
        bankAcNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankAcNumberFocusLost(evt);
            }
        });

        bankIFSC.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                bankIFSCCaretUpdate(evt);
            }
        });
        bankIFSC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankIFSCFocusLost(evt);
            }
        });

        shopName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                shopNameCaretUpdate(evt);
            }
        });
        shopName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                shopNameFocusLost(evt);
            }
        });

        gstin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                gstinCaretUpdate(evt);
            }
        });
        gstin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gstinFocusLost(evt);
            }
        });

        username.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                usernameCaretUpdate(evt);
            }
        });
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });

        error1.setForeground(new java.awt.Color(255, 0, 0));
        error1.setText("error1");

        error2.setForeground(new java.awt.Color(255, 0, 0));
        error2.setText("error2");

        error3.setForeground(new java.awt.Color(255, 0, 0));
        error3.setText("error3");

        error4.setForeground(new java.awt.Color(255, 0, 0));
        error4.setText("error4");

        error5.setForeground(new java.awt.Color(255, 0, 0));
        error5.setText("error5");

        error6.setForeground(new java.awt.Color(255, 0, 0));
        error6.setText("error6");

        error7.setForeground(new java.awt.Color(255, 0, 0));
        error7.setText("error7");

        error8.setForeground(new java.awt.Color(255, 0, 0));
        error8.setText("error8");

        addButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(219, 112, 147));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(219, 112, 147));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        show.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        show.setForeground(new java.awt.Color(219, 112, 147));
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        password.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passwordCaretUpdate(evt);
            }
        });
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bankBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bankAcNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bankIFSC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password)
                                .addGap(2, 2, 2)
                                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(error7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gstin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(error6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shopName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(error5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator7)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bankBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bankAcNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bankIFSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(shopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gstin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(error8)
                    .addComponent(show)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (this.bankName.getSelectedItem().toString().equals(" ") || this.bankBranch.getSelectedItem().toString().equals(" ")
                || this.bankAcNumber.getText().equals("") || this.bankIFSC.getText().equals("")
                || this.shopName.getText().equals(" ") || this.gstin.getText().equals("")
                || this.username.getText().equals("") || this.password.getText().equals("")) {
            if (this.bankName.getSelectedItem().toString().equals(" ")) {
                this.error1.setText("Bank Name Required!");
            }
            if (this.bankBranch.getSelectedItem().toString().equals(" ")) {
                this.error2.setText("Bank Branch Required!");
            }
            if (this.bankAcNumber.getText().equals("")) {
                this.error3.setText("Account Number Required!");
            }
            if (this.bankIFSC.getText().equals("")) {
                this.error4.setText("IFSC Required!");
            }
            if (this.shopName.getText().equals("")) {
                this.error5.setText("Shop Name Required!");
            }
            if (this.gstin.getText().equals("")) {
                this.error6.setText("GSTIN Required!");
            }
            if (this.username.getText().equals("")) {
                this.error7.setText("Username Required!");
            }
            if (this.password.getText().equals("")) {
                this.error8.setText("Password Required!");
            }
            JOptionPane.showMessageDialog(this, "Enter All The Required Information!");
        } else {
            if (this.error1.getText().equals("") && this.error2.getText().equals("")
                    && this.error3.getText().equals("") && this.error4.getText().equals("")
                    && this.error5.getText().equals("") && this.error6.getText().equals("")
                    && this.error7.getText().equals("") && this.error8.getText().equals("")) {
                int ans = JOptionPane.showConfirmDialog(this, "Add Shop?", "Shop Addition", JOptionPane.YES_NO_OPTION);
                if (ans == 0) {
                    bankName2 = (String) this.bankName.getSelectedItem();
                    bankBranch2 = (String) this.bankBranch.getSelectedItem();
                    bankAcNumber2 = this.bankAcNumber.getText();
                    bankIFSC2 = this.bankIFSC.getText();
                    shopName2 = this.shopName.getText();
                    gstin2 = this.gstin.getText();
                    username2 = this.username.getText();
                    password2 = this.password.getText();
                    try {
                        s = c.createStatement();
                        s.executeUpdate("INSERT INTO shop(FIRSTNAME,MIDDLENAME,LASTNAME,STREETADDRESS,CITY,STATE,EMAIL,PHONE,MOBILE,BANKNAME,BANKBRANCH,BANKACNUMBER,BANKIFSC,SHOPNAME,GSTIN,USERNAME,PASSWORD) VALUES('" + firstName3 + "','" + middleName3 + "','" + lastName3 + "','" + streetAddress3 + "','" + city3 + "','" + state3 + "','" + email3 + "','" + phone3 + "','" + mobile3 + "','" + bankName2 + "','" + bankBranch2 + "','" + bankAcNumber2 + "','" + bankIFSC2 + "','" + shopName2 + "','" + gstin2 + "','" + username2 + "','" + password2 + "')");
                        JOptionPane.showMessageDialog(this, "Shop '" + shopName2 + "' Added!");
                        this.dispose();
                        ShopManagementSystem.main(new String[0]);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e);
                    } finally {
                        try {
                            s.close();
                            c.close();
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(this, e);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Details!");
                }
            }
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void bankNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankNameFocusLost
        // TODO add your handling code here:
        String item = this.bankName.getSelectedItem().toString();
        if (!item.equals(" ")) {
            error1.setText("");
        } else {
            error1.setText("Bank Name Required!");
        }
    }//GEN-LAST:event_bankNameFocusLost

    private void bankNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bankNameItemStateChanged
        // TODO add your handling code here:
        String item = this.bankName.getSelectedItem().toString();
        if (!item.equals(" ")) {
            error1.setText("");
        } else {
            error1.setText("Bank Name Required!");
        }
    }//GEN-LAST:event_bankNameItemStateChanged

    private void bankBranchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankBranchFocusLost
        // TODO add your handling code here:
        String item = this.bankBranch.getSelectedItem().toString();
        if (!item.equals(" ")) {
            error2.setText("");
        } else {
            error2.setText("Branch Required!");
        }
    }//GEN-LAST:event_bankBranchFocusLost

    private void bankBranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bankBranchItemStateChanged
        // TODO add your handling code here:
        String item = this.bankBranch.getSelectedItem().toString();
        if (!item.equals(" ")) {
            error2.setText("");
        } else {
            error2.setText("Branch Required!");
        }
    }//GEN-LAST:event_bankBranchItemStateChanged

    private void bankAcNumberCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_bankAcNumberCaretUpdate
        // TODO add your handling code here:
        error3.setText("");
    }//GEN-LAST:event_bankAcNumberCaretUpdate

    private void bankAcNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankAcNumberFocusLost
        // TODO add your handling code here:
        error3.setText("");
        String bankAcNumber1 = this.bankAcNumber.getText();
        if (bankAcNumber1.equals("")) {
            error3.setText("Account Number Required!");
        } else {
            Pattern p = Pattern.compile("^\\d{9,18}$|^$");
            Matcher m = p.matcher(bankAcNumber1);
            if (!m.matches()) {
                error3.setText("Invalid Account Number!");
            }
        }
    }//GEN-LAST:event_bankAcNumberFocusLost

    private void bankIFSCCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_bankIFSCCaretUpdate
        // TODO add your handling code here:
        error4.setText("");
    }//GEN-LAST:event_bankIFSCCaretUpdate

    private void bankIFSCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankIFSCFocusLost
        // TODO add your handling code here:
        error4.setText("");
        String bankIFSC1 = this.bankIFSC.getText();
        if (bankIFSC1.equals("")) {
            error4.setText("IFSC Required!");
        } else {
            Pattern p = Pattern.compile("^[A-Za-z]{4}[a-zA-Z0-9]{7}$|^$");
            Matcher m = p.matcher(bankIFSC1);
            if (!m.matches()) {
                error4.setText("Invalid IFSC!");
            }
        }
    }//GEN-LAST:event_bankIFSCFocusLost

    private void shopNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_shopNameCaretUpdate
        // TODO add your handling code here:
        error5.setText("");
    }//GEN-LAST:event_shopNameCaretUpdate

    private void shopNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_shopNameFocusLost
        // TODO add your handling code here:
        String shopName1 = this.shopName.getText();
        this.error5.setText("");
        if (shopName1.equals("")) {
            this.error5.setText("Shop Name Required!");
        }
    }//GEN-LAST:event_shopNameFocusLost

    private void gstinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_gstinCaretUpdate
        // TODO add your handling code here:
        error6.setText("");
    }//GEN-LAST:event_gstinCaretUpdate

    private void gstinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gstinFocusLost
        // TODO add your handling code here:
        error6.setText("");
        String gstin1 = this.gstin.getText();
        if (gstin1.equals("")) {
            this.error6.setText("GSTIN Required!");
        } else {
            Pattern p = Pattern.compile("^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{3}$|^$");
            Matcher m = p.matcher(gstin1);
            if (!m.matches()) {
                error6.setText("Invalid GSTIN!");
            }
        }
    }//GEN-LAST:event_gstinFocusLost

    private void usernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_usernameCaretUpdate
        // TODO add your handling code here:
        error7.setText("");
    }//GEN-LAST:event_usernameCaretUpdate

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        String username1 = this.username.getText();
        this.error7.setText("");
        if (username1.equals("")) {
            this.error7.setText("Username Required!");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passwordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passwordCaretUpdate
        // TODO add your handling code here:
        this.error8.setText("");
    }//GEN-LAST:event_passwordCaretUpdate

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        String password1 = this.password.getText();
        this.error8.setText("");
        password1 = password1.replaceAll(" ", "");
        if (password1.equals("")) {
            this.error8.setText("Password Required!");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if (a.equals("")) {
            password.setEchoChar((char) 0);
            a = "Set";
            show.setText("Hide");
        } else {
            password.setEchoChar('*');
            a = "";
            show.setText("Show");
        }
    }//GEN-LAST:event_showActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        clearError();
        this.bankName.setSelectedItem(" ");
        this.bankBranch.setSelectedItem(" ");
        clearError();
        this.bankAcNumber.setText("");
        this.bankIFSC.setText("");
        this.shopName.setText("");
        this.gstin.setText("");
        this.username.setText("");
        this.password.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopCreationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopCreationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopCreationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopCreationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopCreationForm3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField bankAcNumber;
    private javax.swing.JComboBox<String> bankBranch;
    private javax.swing.JTextField bankIFSC;
    private javax.swing.JComboBox<String> bankName;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel error5;
    private javax.swing.JLabel error6;
    private javax.swing.JLabel error7;
    private javax.swing.JLabel error8;
    private javax.swing.JTextField gstin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField shopName;
    private javax.swing.JButton show;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
