/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagementsystem;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sultan
 */
public class ShopProfileForm extends javax.swing.JFrame {

    /**
     * Creates new form ShopProfileForm
     */
    Connection c = null;
    Statement s = null;
    ResultSet rs = null;

    public ShopProfileForm() {
        initComponents();

        //Full Screen
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        Image image = new ImageIcon(this.getClass().getResource("Images/image5.png")).getImage();
        Image newImage = image.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageIcon = new ImageIcon(newImage);
        imageLabel.setIcon(newImageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateShopButton = new javax.swing.JButton();
        updateProfileButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        deleteShopButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SHOP PROFILE");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        updateShopButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        updateShopButton.setForeground(new java.awt.Color(219, 112, 147));
        updateShopButton.setText("Update Shop");
        updateShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShopButtonActionPerformed(evt);
            }
        });

        updateProfileButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        updateProfileButton.setForeground(new java.awt.Color(219, 112, 147));
        updateProfileButton.setText("Update Profile");
        updateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(219, 112, 147));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        deleteShopButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        deleteShopButton.setForeground(new java.awt.Color(219, 112, 147));
        deleteShopButton.setText("Delete Shop");
        deleteShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteShopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteShopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateShopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateShopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(updateProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(deleteShopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new WelcomeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShopButtonActionPerformed
        new ShopUpdateForm().setVisible(true);
    }//GEN-LAST:event_updateShopButtonActionPerformed

    private void updateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileButtonActionPerformed
        new ShopProfileUpdateForm().setVisible(true);
    }//GEN-LAST:event_updateProfileButtonActionPerformed

    private void deleteShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteShopButtonActionPerformed
        int ans = JOptionPane.showConfirmDialog(this, "Deleting Shop will delete every details about product, supplier and customer! Delete Shop?", "Shop Deletion", JOptionPane.YES_NO_OPTION);
        if (ans == 0) {
            String password = JOptionPane.showInputDialog(this, "Enter password to delete :");
            try {
                if (!password.equals("")) {
                    try {
                        String id = LoginForm.id.getText();
                        c = DB.java_db();
                        s = c.createStatement();
                        rs = s.executeQuery("SELECT * FROM shop WHERE id=" + id);
                        String password1 = null;
                        while (rs.next()) {
                            password1 = rs.getString("password");
                        }
                        if (password.equals(password1)) {
                            String sql = "DELETE FROM shop WHERE id=" + id;
                            s.executeUpdate(sql);
                            //Customer
                            s.execute("DROP TABLE customer");
                            String sql2 = "CREATE TABLE customer(CUSTOMERID INTEGER PRIMARY KEY AUTOINCREMENT,"
                                    + "CUSTOMERNAME TEXT,MOBILE INTEGER,STREETADDRESS TEXT,CITY TEXT,"
                                    + "STATE TEXT,GSTIN TEXT,PAN TEXT,CUSTOMERBALANCEPAYMENT REAL)";
                            s.executeUpdate(sql2);
                            //Supplier
                            s.execute("DROP TABLE supplier");
                            String sql3 = "CREATE TABLE supplier(SUPPLIERID INTEGER PRIMARY KEY AUTOINCREMENT,"
                                    + "SUPPLIERNAME TEXT,MOBILE INTEGER,STREETADDRESS TEXT,CITY TEXT,"
                                    + "STATE TEXT,GSTIN TEXT,PAN TEXT,SUPPLIERBALANCEPAYMENT REAL)";
                            s.executeUpdate(sql3);
                            //Product
                            s.execute("DROP TABLE product");
                            String sql4 = "CREATE TABLE product(PRODUCTID INTEGER PRIMARY KEY AUTOINCREMENT,"
                                    + "PRODUCTNAME TEXT,HSN TEXT,MEASURINGUNIT TEXT,GST TEXT,"
                                    + "PURCHASERATE REAL,BASICPURCHASERATE REAL,BASICSALERATE REAL,SALERATE REAL,"
                                    + "SAFETYSTOCK INTEGER DEFAULT 0,QUANTITY INTEGER DEFAULT 0)";
                            s.executeUpdate(sql4);
                            //Purchase Details
                            s.execute("DROP TABLE ptdetails");
                            String sql5 = "CREATE TABLE ptdetails(PTDID INTEGER PRIMARY KEY AUTOINCREMENT,"
                                    + "BILLNO TEXT,TDATE TEXT,SUPPLIERID INTEGER,PRODUCTID INTEGER,QUANTITY INTEGER,"
                                    + "TAXABLEAMOUNT REAL,CGSTP REAL,CGSTA REAL,SGSTP REAL,"
                                    + "SGSTA REAL,TOTALAMOUNT REAL)";
                            s.executeUpdate(sql5);
                            //Sale Details
                            s.execute("DROP TABLE stdetails");
                            String sql6 = "CREATE TABLE stdetails(STDID INTEGER PRIMARY KEY AUTOINCREMENT,"
                                    + "BILLNO TEXT,TDATE TEXT,CUSTOMERID INTEGER,PRODUCTID INTEGER,QUANTITY INTEGER,"
                                    + "TAXABLEAMOUNT REAL,CGSTP REAL,CGSTA REAL,SGSTP REAL,"
                                    + "SGSTA REAL,TOTALAMOUNT REAL)";
                            s.executeUpdate(sql6);
                            //Purchase
                            s.execute("DROP TABLE purchasetransaction");
                            String sql7 = "CREATE TABLE purchasetransaction(TID INTEGER PRIMARY KEY AUTOINCREMENT,"
                                    + "BILLNO TEXT,TDATE TEXT,SUPPLIERID INTEGER,TOTALAMOUNT REAL,"
                                    + "DISCOUNTP REAL,DISCOUNTR REAL,GRANDTOTAL REAL,PAIDAMOUNT REAL)";
                            s.executeUpdate(sql7);
                            //Sale
                            s.execute("DROP TABLE saletransaction");
                            String sql8 = "CREATE TABLE saletransaction(TID INTEGER PRIMARY KEY AUTOINCREMENT,"
                                    + "BILLNO TEXT,TDATE TEXT,CUSTOMERID INTEGER,TOTALAMOUNT REAL,"
                                    + "DISCOUNTP REAL,DISCOUNTR REAL,GRANDTOTAL REAL,PAIDAMOUNT REAL)";
                            s.executeUpdate(sql8);
                            JOptionPane.showMessageDialog(this, "Shop Deleted Successfully!");
                            this.dispose();
                            ShopManagementSystem.main(new String[0]);
                        } else {
                            JOptionPane.showMessageDialog(this, "Incorrect Password!");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e);
                    } finally {
                        try {
                            rs.close();
                            s.close();
                            c.close();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, e);
                        }
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_deleteShopButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new WelcomeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopProfileForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteShopButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton updateProfileButton;
    private javax.swing.JButton updateShopButton;
    // End of variables declaration//GEN-END:variables
}
