/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagementsystem;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sultan
 */
public class WelcomeForm extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeForm
     */
    String shopName1;
    Connection c = null;
    Statement s = null;
    ResultSet rs = null;

    public WelcomeForm() {
        initComponents();

        //Full Screen
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        //Getting shop name & first name from LoginForm.java & database
        String id1 = LoginForm.id.getText();
        shopName1 = LoginForm.shopName.getSelectedItem().toString();
        try {
            c = DB.java_db();
            s = c.createStatement();
            rs = s.executeQuery("SELECT * FROM shop WHERE id=" + id1);
            String firstName1 = "", lastName1 = "";
            while (rs.next()) {
                firstName1 = rs.getString("firstName");
                lastName1 = rs.getString("lastName");
            }
            welcomeMessage.setText("Welcome " + firstName1 + " " + lastName1 + "! Connected To Shop : " + shopName1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(WelcomeForm.this, e);
        } finally {
            try {
                rs.close();
                s.close();
                c.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(WelcomeForm.this, e);
            }
        }

        //Setting up image
        Image image = new ImageIcon(this.getClass().getResource("Images/image1.png")).getImage();
        Image newImage = image.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageIcon = new ImageIcon(newImage);
        imageLabel.setIcon(newImageIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMessage = new javax.swing.JLabel();
        productButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        purchaseProductButton = new javax.swing.JButton();
        shopProfileButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        supplierButton = new javax.swing.JButton();
        sellProductButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("WELCOME");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        welcomeMessage.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        welcomeMessage.setForeground(new java.awt.Color(0, 204, 102));
        welcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeMessage.setText("Welcome");

        productButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        productButton.setForeground(new java.awt.Color(219, 112, 147));
        productButton.setText("Product");
        productButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonActionPerformed(evt);
            }
        });

        customerButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        customerButton.setForeground(new java.awt.Color(219, 112, 147));
        customerButton.setText("Customer");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });

        purchaseProductButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        purchaseProductButton.setForeground(new java.awt.Color(219, 112, 147));
        purchaseProductButton.setText("Purchase Product");
        purchaseProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseProductButtonActionPerformed(evt);
            }
        });

        shopProfileButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        shopProfileButton.setForeground(new java.awt.Color(219, 112, 147));
        shopProfileButton.setText("Shop Profile");
        shopProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopProfileButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(219, 112, 147));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        supplierButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        supplierButton.setForeground(new java.awt.Color(219, 112, 147));
        supplierButton.setText("Supplier");
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });

        sellProductButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        sellProductButton.setForeground(new java.awt.Color(219, 112, 147));
        sellProductButton.setText("Sell Product");
        sellProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellProductButtonActionPerformed(evt);
            }
        });

        reportsButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(219, 112, 147));
        reportsButton.setText("Reports");
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shopProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(purchaseProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(productButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(sellProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(customerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(supplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(welcomeMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sellProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shopProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonActionPerformed
        //will dispose this form and open ProductForm.java
        new ProductForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        //will dispose this form and open LoginForm.java if user clicks Yes button
        int ans = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Logout?", JOptionPane.YES_NO_OPTION);
        if (ans == 0) {
            java.awt.Window win[] = java.awt.Window.getWindows();
            for (int i = 0; i < win.length; i++) {
                win[i].dispose();
            }
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            LoginForm.shopName.setSelectedItem(shopName1);

            this.dispose();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        //will dispose this form and open CustomerForm.java
        new CustomerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerButtonActionPerformed

    private void shopProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopProfileButtonActionPerformed
        //will dispose this form and open ShopProfileForm.java
        new ShopProfileForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shopProfileButtonActionPerformed

    private void purchaseProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseProductButtonActionPerformed
        //will open PurchaseProductForm.java
        new PurchaseProductForm().setVisible(true);
    }//GEN-LAST:event_purchaseProductButtonActionPerformed

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        //will dispose this form and open SupplierForm.java
        new SupplierForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplierButtonActionPerformed

    private void sellProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellProductButtonActionPerformed
        //will open SellProductForm.java
        new SellProductForm().setVisible(true);
    }//GEN-LAST:event_sellProductButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        //will open ReportsForm.java
        new ReportsForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Logout?", JOptionPane.YES_NO_OPTION);
        if (ans == 0) {
            java.awt.Window win[] = java.awt.Window.getWindows();
            for (int i = 0; i < win.length; i++) {
                win[i].dispose();
            }
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            LoginForm.shopName.setSelectedItem(shopName1);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton productButton;
    private javax.swing.JButton purchaseProductButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JButton sellProductButton;
    private javax.swing.JButton shopProfileButton;
    private javax.swing.JButton supplierButton;
    private javax.swing.JLabel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
